sudo: required
language: java
jdk: openjdk11
services:
- docker
addons:
  apt:
    packages:
    - python3
    - python3-pip
before_install:
  - pyenv global 3.7.1
  - python --version
  - pip install -U pip
  - pip install awscli --upgrade --user

script: 
- mvn clean install jacoco:report
- mvn package com.google.cloud.tools:jib-maven-plugin:dockerBuild -pl backend

after_success:
- mvn jacoco:report

# push image to ecr
# create fargate task, service, load balancer, certificate
# run fargate

cache:
  directories:
  - node_modules
