sudo: required
language: java
jdk: openjdk11
services:
  - docker
env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - which python
  - which pyenv
  - pyenv versions
  # pyenv global 3.8
  - pyenv global 3.7.1
  - python -VV
  - pip -V
  - pip install --user awscli
  - aws help

script: 
  - mvn clean package
  - mvn com.google.cloud.tools:jib-maven-plugin:dockerBuild -pl backend

after_success:
  - mvn jacoco:report

# push image to ecr
# create fargate task, service, load balancer, certificate
# run fargate

cache:
  directories:
    - node_modules
